### ISSUE TITLE
Nuget Package Request

### ISSUE THREAD

**Issue by chrpai** [tpalacino/GlobalParams#1]
I've been removing all the DLLs from my repos and replacing them with Nuget packages where possible.  Would it be possible to get GlobalParmas published?   I can submit a PR  for the nuspec file if you'd like.

I could publish it myself but I don't care for the pattern of people submitting unofficial packages.  I'd rather see it come from the horses mouth.

**Comment by tpalacino** [comment]
[Nuget Package](https://www.nuget.org/packages/GlobalParams) has been published. It will be available in package search results when indexing is complete.

**Comment by chrpai** [comment]
Thanks!
