### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by chrpai** [tpalacino/GlobalParams#3]
VS2022 made changes to it's SDK.  When I create a project that uses GlobalParams I get the error:

Method nout found: 'EnvDTE.solution EnvDITE._DTE.get_Solution();

I've googled this error and found suggestions to only use EnvDTE2.  Not sure if that will help or not. 

![image](https://user-images.githubusercontent.com/43178814/152721949-6930cad0-1538-44c5-98a0-e9626e71770f.png)

**Comment by chrpai** [comment]
I've worked this out and have a PR.  This does require going from .NET 3.5 to 4.7.2. 

https://github.com/tpalacino/GlobalParams/pull/4

**Comment by tpalacino** [comment]
Closed as fixed by @chrpai in PR #4

**Comment by tpalacino** [comment]
@chrpai The [Nuget package](https://www.nuget.org/packages/GlobalParams/2.0.0) has been updated with this target framework fix
